### ISSUE TITLE
How to compile

### ISSUE THREAD

**Issue by KHome** [arhi/EthernetSPI2#2]
Hi,

I've got an error while compiling in Arduino IDE and / or Plattform.io.
Can you give me a hint how to use the code?

Is the SPI Version solved with new Arduino Ethernet approach?

BR

**Comment by arhi** [comment]
Make sure you have this repo unpacked in your Documents/Arduino/libraries/EthernetSPI2
start arduino
select board "AI Thinker ESP32-CAM"

![image](https://user-images.githubusercontent.com/410177/164069588-f14c05cf-c819-494b-9a50-e8c99ea19e14.png)

copy the content of the ESP32EthCamera.ino file (you can find it in examples in this library) to your sketch and click compile

![image](https://user-images.githubusercontent.com/410177/164070354-68bef336-8456-4563-88cb-e3c97acd2675.png)


after it compiles, click to upload to your board

then edit the example to suit your needs...
